### ISSUE TITLE
Docker installation with Kubernetes

### ISSUE THREAD

**Issue by fbecart** [vasanthdeveloper/ghata#21]
Hi, I previously successfully installed Ghata on a DigitalOcean droplet using this documentation: https://github.com/vasanthdeveloper/ghata/blob/mainline/docs/install/typical.md

I'm now experimenting with a Kubernetes setup (similar to https://teilin.net/getting-started-with-kubernetes/). Using the same DigitalOcean space configuration as previously, I'm updating my container with the following:

- the install command

```yaml
        - name: ghost
          image: ghost:3.41-alpine
          command: ["sh"]
          args: ["-c", 'sh -c "npx ghata --auto --verbose" && node current/index.js']
```

- the env variables

```yaml
          env:
            - name: GHATA_CONFIG
              value: config.production.json
            - name: GHATA_ENDPOINT
              value: [redacted]
            - name: GHATA_BUCKET
              value: [redacted]
            - name: GHATA_SUBDOMAIN
              value: [redacted]
            - name: GHATA_PATH
              value: [redacted]
            - name: GHATA_KEY
              value: [redacted]
            - name: GHATA_SECRET
              value: [redacted]
```

At startup, I get the following logs:

```
npx: installed 196 in 24.723s
verbose GHATA_CONFIG  config.production.json
verbose GHATA_ENDPOINT  [redacted]
verbose GHATA_BUCKET  [redacted]
verbose GHATA_PATH  [redacted]
verbose GHATA_KEY  [redacted]
verbose GHATA_SECRET  [hidden]
verbose Installing dependencies required for ghata
verbose Executing: yarn add aws-sdk@2.670.0
```

Nothing more. Ghost is unreachable and I don't get the usual Ghost startup logs. How could I debug the issue further?

Also, after a solution is found, I'll look into embedding Ghata into the Docker image to speed up the startup time. Any hint would be welcome.
